# Generated by Django 4.2.10 on 2024-10-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cidade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.curso')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registro', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('semestre', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.professor')),
            ],
            options={
                'ordering': ['ano', 'semestre', 'curso'],
                'unique_together': {('curso', 'professor', 'ano', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma')),
            ],
            options={
                'ordering': ['turma', 'disciplina', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('data_avaliacao', models.DateField(verbose_name='Data de Avaliação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma')),
            ],
            options={
                'ordering': ['data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(verbose_name='Data de Matrícula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='cadastros.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma')),
            ],
            options={
                'ordering': ['data_matricula'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.AddConstraint(
            model_name='horarioaula',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina', 'dia_semana', 'hora_inicio'), name='unique_horario_aula'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nome', 'curso')},
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.CheckConstraint(check=models.Q(('nota__gte', 0), ('nota__lte', 10)), name='nota_range'),
        ),
    ]
